---
- hosts: web
  become: yes
  tasks:
  - name: Install httpd 
    package:
      name: httpd
      state: present

  - name: start service
    service:
      name: httpd
      state: started
      enabled: yes  
  
  - name: update file
    copy:
      dest: /var/www/html/index.html
      content: <h1>Welcome to Apache-Rav</h1>


...
