---
- hosts: web
  become: yes
  tasks:
  - name: Install httpd 
    package:
      name: httpd
      state: present
 
  - name: update file
    copy:
      dest: /var/www/html/index.html
      content: <h1>Welcome to Apache-Rav</h1>

  - name: update Apache port config
    copy:
      dest: /etc/httpd/conf/httpd.conf
      src: /home/centos/playbooks/httpd.conf

  - name:  Enable SElinux
    selinux:
      policy: targeted
      state: permissive

  - name: Restart service
    service:
      name: httpd
      state: restarted

  - name: start service
    service:
      name: httpd
      state: started
      enabled: yes  
  

...
