---
- hosts: web
  become: yes
  handlers: 
  - name: Restart Apache
    service:
      name: httpd
      state: restarted

  - name: start service
    service:
      name: httpd
      state: started
      enabled: yes  
 
  tasks:
  - name: Install httpd 
    package:
      name: httpd
      state: present
    notify: 
      -Start Apache  

  - name:  Enable SElinux
    selinux:
      policy: targeted
      state: permissive

  - name: update file
    copy:
      dest: /var/www/html/index.html
      content: <h1>Welcome to Apache-Rav</h1>

  - name: update Apache port config
    copy:
      dest: /etc/httpd/conf/httpd.conf
      src: /home/centos/playbooks/httpd.conf
    notify:
      - Restart Apache  

  - name: update PHP page
    copy:
      dest: /var/www/html/date.php
      src: /home/centos/playbooks/date.php

  - name: Install PHP 
    package:
      name: php
      state: present
    notify:
      - Restart Apache       
...
